"""initial schema

Revision ID: ed2f4c6868ff
Revises: 
Create Date: 2026-02-27 21:57:52.113869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2f4c6868ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('TASK', 'FEATURE_REQUEST', 'ESCALATION', name='externalticketentitytype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_system', sa.Enum('JIRA', 'ZENDESK', 'OTHER', name='externalticketsystem'), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status_cache', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_tickets_entity_id'), 'external_tickets', ['entity_id'], unique=False)
    op.create_table('tag_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('ESCALATION', 'FEATURE_REQUEST', 'SENTIMENT', 'CUSTOM', name='tagcategory'), nullable=False),
    sa.Column('sentiment', sa.Enum('NEGATIVE', 'NEUTRAL', 'POSITIVE', name='tagsentiment'), nullable=True),
    sa.Column('auto_action', sa.Enum('CREATE_ESCALATION', 'CREATE_FEATURE_REQUEST', 'NONE', name='tagautoaction'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_definitions_name'), 'tag_definitions', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'LEAD', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('PROJECT', 'PHASE', 'TASK', 'FEATURE_REQUEST', 'ESCALATION', name='attachmententitytype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('PROJECT', 'PHASE', 'TASK', 'FEATURE_REQUEST', 'ESCALATION', name='noteentitytype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_entity_id'), 'notes', ['entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TASK_DUE_SOON', 'TASK_OVERDUE', 'PROJECT_INACTIVE', 'PHASE_COMPLETED', 'ESCALATION_OPENED', 'TAG_ESCALATION_DETECTED', 'MENTION', 'REPORT_READY', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'AT_RISK', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.Enum('KICKOFF', 'DESIGN', 'IMPLEMENT', 'DEPLOY', name='currentphase'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_customer_name'), 'projects', ['customer_name'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('page', sa.String(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_views_user_id'), 'saved_views', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_project_id'), 'contacts', ['project_id'], unique=False)
    op.create_table('health_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.Enum('PROJECT_HEALTH', 'AGGREGATE', 'NL_QUERY', name='reporttype'), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('blocks_json', sa.JSON(), nullable=True),
    sa.Column('report_data_json', sa.JSON(), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('KICKOFF', 'DESIGN', 'IMPLEMENT', 'DEPLOY', name='phasename'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', name='phasestatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_phase_name')
    )
    op.create_index(op.f('ix_phases_project_id'), 'phases', ['project_id'], unique=False)
    op.create_table('tag_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('NOTE', 'TASK', 'EXTERNAL_TICKET', name='tagentitytype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('derived_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_events_entity_id'), 'tag_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tag_events_project_id'), 'tag_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_tag_events_tag_id'), 'tag_events', ['tag_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('matrix_quadrant', sa.Enum('DO', 'SCHEDULE', 'DELEGATE', 'ELIMINATE', name='matrixquadrant'), nullable=True),
    sa.Column('matrix_override', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_phase_id'), 'tasks', ['phase_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='escalationseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='escalationstatus'), nullable=False),
    sa.Column('raised_by', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'TAG_DERIVED', name='escalationsource'), nullable=False),
    sa.Column('source_note_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_project_id'), 'escalations', ['project_id'], unique=False)
    op.create_table('feature_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('why_important', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='featurerequestpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'PLANNED', 'SHIPPED', 'DECLINED', name='featurerequeststatus'), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'TAG_DERIVED', name='featurerequestsource'), nullable=False),
    sa.Column('source_note_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_requests_project_id'), 'feature_requests', ['project_id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_assignees')
    op.drop_index(op.f('ix_feature_requests_project_id'), table_name='feature_requests')
    op.drop_table('feature_requests')
    op.drop_index(op.f('ix_escalations_project_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_phase_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_tag_events_tag_id'), table_name='tag_events')
    op.drop_index(op.f('ix_tag_events_project_id'), table_name='tag_events')
    op.drop_index(op.f('ix_tag_events_entity_id'), table_name='tag_events')
    op.drop_table('tag_events')
    op.drop_index(op.f('ix_phases_project_id'), table_name='phases')
    op.drop_table('phases')
    op.drop_table('health_reports')
    op.drop_index(op.f('ix_contacts_project_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_saved_views_user_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_projects_customer_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notes_entity_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tag_definitions_name'), table_name='tag_definitions')
    op.drop_table('tag_definitions')
    op.drop_index(op.f('ix_external_tickets_entity_id'), table_name='external_tickets')
    op.drop_table('external_tickets')
    # ### end Alembic commands ###
